# Generated by Django 2.1.5 on 2019-04-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/b/b9/No_Cover.jpg', max_length=1000),
        ),
    ]
