# Generated by Django 2.1.5 on 2019-04-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_savedforlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.BookDetails'),
        ),
        migrations.AlterField(
            model_name='savedforlater',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.BookDetails'),
        ),
    ]
