# Generated by Django 2.1.5 on 2019-04-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('authorbio', models.CharField(max_length=200)),
                ('authorhyperlink', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('publisherinfo', models.CharField(max_length=200)),
                ('coverphotourl', models.CharField(max_length=200)),
            ],
        ),
    ]
