# Generated by Django 2.1.5 on 2019-04-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='coverphotourl',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/b/b9/No_Cover.jpg', max_length=1000),
        ),
    ]
